# ansible-playbook pb_aap_config.yml --tags linux,credentials --skip-tags common
---
controller_credentials_linux:
  - name: Daily Demo [Autodotes]
    organization: Autodotes
    description: used for daily demo
    credential_type: Daily Demo Credential
    inputs:
      controller_passwd: REPLACE_ME
      customer_portal_passwd: REPLACE_ME
  - name: Daily Demo Vault Password
    organization: Autodotes
    description: decrypt vaulted password file for daily demo
    credential_type: Vault
    inputs:
      vault_id: ""
      vault_password: REPLACE_ME
  - name: Demo Vault
    organization: Autodotes
    description: decrypt vaulted password file for demo
    credential_type: Vault
    inputs:
      vault_password: "{{ controller_credential_ansible_vault_password }}"
  - name: RHSM (zachleblanc)
    organization: Autodotes
    description: Red Hat account RHSM
    credential_type: Red Hat Subscription Manager
    inputs:
      rhsm_password: "{{ controller_credential_redhat_zachleblanc }}"
      rhsm_user: zachleblanc
  - name: Satellite Provisioner
    organization: Autodotes
    description: ""
    credential_type: Machine
    inputs:
      become_method: ""
      become_password: REPLACE_ME
      become_username: ""
      password: REPLACE_ME
      username: ansible
