# ansible-playbook pb_aap_config.yml --tags linux,credential_types --skip-tags common
---
controller_credential_types_linux:
  - name: Daily Demo Credential
    description: for use with Eric Ames daily demo
    kind: cloud
    inputs:
      fields:
        - id: controller_passwd
          label: Controller Password
          secret: true
          type: string
        - id: customer_portal_passwd
          label: Customer Portal Password
          secret: true
          type: string
      required:
        - controller_passwd
        - customer_portal_passwd
    injectors:
      extra_vars:
        controller_passwd: !unsafe "{{ controller_passwd }}"
        customer_portal_passwd: !unsafe "{{ customer_portal_passwd }}"
  - name: Red Hat Subscription Manager
    description: for integration with Red Hat Subscription Manager
    kind: cloud
    inputs:
      fields:
        - id: rhsm_user
          label: RHSM Username
          type: string
        - id: rhsm_password
          label: RHSM Password
          secret: true
          type: string
      required:
        - rhsm_user
        - rhsm_password
    injectors:
      extra_vars:
        customer_portal_password: !unsafe "{{ rhsm_password }}"
        customer_portal_username: !unsafe "{{ rhsm_user }}"
        rhsm_password: !unsafe "{{ rhsm_password }}"
        rhsm_user: !unsafe "{{ rhsm_user }}"
