# ansible-playbook pb_aap_config.yml --tags linux,projects --skip-tags common
---
controller_projects_linux:
  - name: Lockdown RHEL8 CIS
    organization: Autodotes
    scm_type: git
    scm_url: https://github.com/ansible-lockdown/RHEL8-CIS.git
    default_environment: ee-default
  - name: RH Gov Samples
    organization: Default
    scm_type: git
    scm_url: https://github.com/RedHatGov/ansible-tower-samples
    scm_branch: product-demos
  - name: "[Ext] aap.dailydemos.linux"
    organization: Autodotes
    scm_type: git
    scm_url: https://github.com/ericcames/aap.dailydemo.linux.git
    scm_branch: main
    default_environment: ee-default
