# ansible-playbook pb_aap_config.yml --tags hashi,credential_types --skip-tags common
---
controller_credential_types_hashi:
  - name: Terraform Cloud Token
    description: Credential to inject krb5 conf and supply username/password for generating a ticket
    kind: cloud
    inputs:
      fields:
        - id: hcp_hostname
          type: string
          label: Hostname
          default: app.terraform.io
        - id: hcp_organization
          type: string
          label: Organization
        - id: hcp_workspace
          type: string
          label: Workspace
        - id: hcp_token
          type: string
          label: Token
          secret: true
      required:
        - hcp_hostname
        - hcp_token
    injectors:
      file:
        template: !unsafe |-
          {
            "credentials": {
              "{{ hcp_hostname }}": {
                "token": "{{ hcp_token }}"
              }
            }
          }
      env:
        TF_WORKSPACE: !unsafe "{{ hcp_workspace }}"
        TF_CLOUD_HOSTNAME: !unsafe "{{ hcp_hostname }}"
        TF_CLOUD_ORGANIZATION: !unsafe "{{ hcp_organization }}"
        TF_CLI_CONFIG_FILE: !unsafe "{{ tower.filename }}"
  - name: Terraform Cloud API
    description: for integration with the Tf Cloud API
    kind: cloud
    inputs:
      fields:
        - id: tf_base_url
          label: Tf Cloud API Host
          type: string
        - id: tf_api_token
          label: Tf Cloud API Token
          secret: true
          type: string
        - id: tf_organization
          label: Tf Organization
          type: string
        - id: tf_workspace
          label: Tf Worksapce
          type: string
      required:
        - tf_base_url
        - tf_api_token
    injectors:
      env:
        TF_HOSTNAME: !unsafe "{{ tf_base_url }}"
        TF_TOKEN: !unsafe "{{ tf_api_token }}"
      extra_vars:
        tf_api_token: !unsafe "{{ tf_api_token }}"
        tf_base_url: !unsafe "{{ tf_base_url }}"
        tf_organization: !unsafe "{{ tf_organization }}"
        tf_workspace: !unsafe "{{ tf_workspace }}"
  - name: HashiCorp Vault Credential
    description: HashiCorp Vault credential for use with community.hashi_vault collection
    kind: cloud
    inputs:
      fields:
        - id: vault_addr
          label: Vault Address
          type: string
        - id: vault_namespace
          label: Vault Namespace
          type: string
        - id: vault_token
          label: Vault Token
          secret: true
          type: string
        - id: vault_ca_cert
          label: Vault CA Certificate
          type: string
        - default: false
          id: vault_skip_verify
          label: Skip SSL Verification
          type: boolean
      required:
        - vault_addr
    injectors:
      env:
        VAULT_ADDR: !unsafe "{{ vault_addr }}"
        VAULT_CACERT: !unsafe "{{ vault_ca_cert }}"
        VAULT_NAMESPACE: !unsafe "{{ vault_namespace }}"
        VAULT_SKIP_VERIFY: !unsafe "{{ vault_skip_verify }}"
        VAULT_TOKEN: !unsafe "{{ vault_token }}"
  - name: Vault Demo Credential Type
    description: For integration with HashiCorp Vault
    kind: cloud
    inputs:
      fields:
        - id: vault_demo_username
          label: Username
          type: string
        - id: vault_demo_password
          label: Password
          secret: true
          type: string
      required:
        - vault_demo_username
        - vault_demo_password
    injectors:
      env:
        VAULT_DEMO_PASSWORD: !unsafe "{{ vault_demo_password }}"
        VAULT_DEMO_USER: !unsafe "{{ vault_demo_username }}"
      extra_vars:
        vault_demo_password: !unsafe "{{ vault_demo_password }}"
        vault_demo_user: !unsafe "{{ vault_demo_username }}"
