# ansible-playbook pb_aap_config.yml --tags hashi,credential_input_sources --skip-tags common
---
controller_credential_input_sources_hashi:
  - source_credential: Vault OIDC Lookup
    target_credential: Vault OIDC Allow
    input_field_name: generic_token
    metadata:
      secret_path: secret/data/aap/Autodotes/autodotes-sa
      secret_key: client_id
      default_auth_path: jwt
  - source_credential: Vault OIDC Lookup
    target_credential: Vault OIDC Deny
    input_field_name: generic_token
    metadata:
      secret_path: secret/data/aap/Default/autodotes-sa
      secret_key: client_id
      default_auth_path: jwt
