# ansible-playbook pb_aap_config.yml --tags hashi,credentials --skip-tags common
---
controller_credentials_hashi:
  - name: AAP (tf)
    organization: Autodotes
    description: SSH credential for connecting as zach user
    credential_type: Machine
    inputs:
      become_method: ""
      become_username: ""
      ssh_key_data: "{{ controller_credential_tf_ssh_key }}"
      username: zach
  - name: Terraform (zleblanc)
    organization: Autodotes
    credential_type: Terraform Cloud API
    inputs:
      tf_base_url: "{{ controller_credential_tf_base_url }}"
      tf_api_token: "{{ controller_credential_tf_api_token }}"
  - name: app.terraform.io/zleblanc/azure-web-demo-dev/backend
    organization: Autodotes
    description: Terraform backend configuration from HCP workspace
    credential_type: Terraform backend configuration
    inputs:
      configuration: |
        token = "{{ controller_credential_hcp_token }}"
        organization =  "zleblanc"
        hostname = "app.terraform.io"
        workspaces { name = "azure-web-demo-dev" }
  - name: app.terraform.io/zleblanc/azure-web-demo-dev
    organization: Autodotes
    description: Integration with HCP from cloud.terraform
    credential_type: Terraform Cloud Token
    inputs:
      hcp_hostname: app.terraform.io
      hcp_organization: zleblanc
      hcp_workspace: azure-web-demo-dev
      hcp_token: "{{ controller_credential_hcp_token }}"
  - name: app.terraform.io/zleblanc/aws-web-demo-dev/backend
    organization: Autodotes
    description: Terraform backend configuration from HCP workspace
    credential_type: Terraform backend configuration
    inputs:
      configuration: |
        token = "{{ controller_credential_hcp_token }}"
        organization =  "zleblanc"
        hostname = "app.terraform.io"
        workspaces { name = "aws-web-demo-dev" }
  - name: app.terraform.io/zleblanc/aws-web-demo-dev
    organization: Autodotes
    description: Integration with HCP from cloud.terraform
    credential_type: Terraform Cloud Token
    inputs:
      hcp_hostname: app.terraform.io
      hcp_organization: zleblanc
      hcp_workspace: aws-web-demo-dev
      hcp_token: "{{ controller_credential_hcp_token }}"
  - name: Azure Terraform Backend Configuration
    organization: Autodotes
    description: Terraform backend configuration for Azure storage account in open environment
    credential_type: Terraform backend configuration
    inputs:
      configuration: |
        resource_group_name  = "openenv-dgzlg"
        storage_account_name = "zjltfstatemgmtsa"
        container_name       = "tfstate"
        use_azuread_auth     = true
        tenant_id            = "{{ controller_credential_azure_tenant }}"
        client_id            = "{{ controller_credential_azure_client }}"
        client_secret        = "{{ controller_credential_azure_secret }}"
  - name: Azure Open Environment Service Principal
    organization: Autodotes
    description: Service Principal for Azure open env
    credential_type: Microsoft Azure Resource Manager
    inputs:
      subscription: "{{ controller_credential_azure_subscription }}"
      tenant: "{{ controller_credential_azure_tenant }}"
      client: "{{ controller_credential_azure_client }}"
      secret: "{{ controller_credential_azure_secret }}"
  - name: HashiCorp Vault Lookup Integration (root)
    organization: Autodotes
    description: ""
    credential_type: HashiCorp Vault Secret Lookup
    inputs:
      api_version: v1
      cacert: ""
      default_auth_path: ""
      kubernetes_role: ""
      namespace: ""
      role_id: ""
      token: REPLACE_ME
      url: https://vault.autodotes.com:2083
      username: ""
  - name: HashiCorp Vault Lookup Plugin (root)
    organization: Autodotes
    description: ""
    credential_type: HashiCorp Vault Credential
    inputs:
      vault_addr: https://vault.autodotes.com:2083
      vault_ca_cert: ""
      vault_namespace: ""
      vault_skip_verify: false
      vault_token: REPLACE_ME
  - name: Vault Demo Credential
    organization: Autodotes
    description: ""
    credential_type: Vault Demo Credential Type
    inputs:
      vault_demo_password: REPLACE_ME
      vault_demo_username: demo-user
  - name: Vault OIDC Lookup
    organization: Autodotes
    description: Vault lookup for OIDC integration
    credential_type: HashiCorp Vault Secret Lookup (OIDC)
    inputs:
      url: https://vault.autodotes.com:8200
      api_version: v1
      default_auth_path: jwt
      jwt_role: aap-role-dynamic
  - name: Vault OIDC Allow
    organization: Autodotes
    credential_type: Generic Token
  - name: Vault OIDC Deny
    organization: Autodotes
    credential_type: Generic Token
