# ansible-playbook pb_aap_config.yml --tags hashi,workflow_job_templates --skip-tags common
---
controller_workflows_hashi:
  - name: Terraform // Azure Deploy and Configure Workflow
    organization: Autodotes
    labels:
      - Hashi
    survey_enabled: true
    survey_spec:
      name: workflow survey
      description: SSH public key passthrough
      spec:
        - question_name: SSH Public Key
          question_description: SSH public key which will enable configuration after provisioning
          max: 1024
          min: 1
          required: true
          type: password
          variable: az_ssh_pubkey
        - question_name: Azure VM Size
          question_description: size of the Azure VMs
          max: 30
          min: 1
          required: true
          default: Standard_DS1_v2
          type: text
          variable: az_web_vm_size
    workflow_nodes:
      - identifier: Sync Project
        related:
          success_nodes:
            - identifier: Terraform Create
        unified_job_template:
          name: Terraform Mgmt
          organization:
            name: Autodotes
            type: organization
          type: project
      - identifier: Terraform Create
        related:
          failure_nodes:
            - identifier: Terraform Destroy
          success_nodes:
            - identifier: Sync Terraform Inventory
        unified_job_template:
          name: Terraform // Azure Web Demo Deploy
          organization:
            name: Autodotes
            type: organization
          type: job_template
      - identifier: Sync Terraform Inventory
        related:
          success_nodes:
            - identifier: Configure Web Servers
        unified_job_template:
          inventory:
            name: Ansible-Terraform Inventory
            organization:
              name: Autodotes
              type: organization
            type: inventory
          name: Azure Open Environment
          type: inventory_source
      - identifier: Configure Web Servers
        related:
          failure_nodes:
            - identifier: Terraform Destroy
        unified_job_template:
          name: Terraform // Azure Web Demo Configure
          organization:
            name: Autodotes
            type: organization
          type: job_template
      - identifier: Terraform Destroy
        job_tags: remove
        unified_job_template:
          name: Terraform // Azure Web Demo Deploy
          organization:
            name: Autodotes
            type: organization
          type: job_template
  - name: Terraform // HCP // Azure Deploy and Configure Workflow
    organization: Autodotes
    labels:
      - Hashi
    ask_variables_on_launch: true
    ask_labels_on_launch: true
    survey_enabled: true
    survey_spec:
      name: workflow survey
      description: SSH public key passthrough
      spec:
        - question_name: SSH Public Key
          question_description: SSH public key which will enable configuration after provisioning
          max: 1024
          min: 1
          required: true
          type: password
          variable: az_ssh_pubkey
        - question_name: Azure VM Size
          question_description: size of the Azure VMs
          max: 30
          min: 1
          required: true
          default: Standard_DS1_v2
          type: text
          variable: az_web_vm_size
        - question_name: AAP Hostname
          question_description: Used for documentation of job and workflow details
          max: 100
          min: 1
          required: false
          default: ansible.autodotes.com
          type: text
          variable: aap_host
    workflow_nodes:
      - identifier: Sync Terraform Project
        related:
          success_nodes:
            - identifier: Terraform Create
        unified_job_template:
          name: Terraform Mgmt
          organization:
            name: Autodotes
            type: organization
          type: project
      - identifier: Sync Cloud Project
        related:
          success_nodes:
            - identifier: Create Tf Task
        unified_job_template:
          name: Cloud Mgmt
          organization:
            name: Autodotes
            type: organization
          type: project
      - identifier: Create Tf Task
        related:
          success_nodes:
            - identifier: Terraform Create
        extra_data:
          _hosts: localhost
          sn_manage_action: create
          sn_resource: sc_task
          create_sc_task_data_overrides:
            localhost:
              short_description: Ansible initiating Terraform deployment of resources to Azure
        inventory: Ansible-HCP Inventory
        unified_job_template:
          name: ServiceNow // Manage Resources
          organization:
            name: Autodotes
            type: organization
          type: job_template
      - identifier: Terraform Create
        related:
          failure_nodes:
            - identifier: Terraform Destroy
            - identifier: Update Tf Task (Sad)
          success_nodes:
            - identifier: Update Tf Task (Happy)
        all_parents_must_converge: true
        unified_job_template:
          name: Terraform // HCP // Azure Web Demo Deploy
          organization:
            name: Autodotes
            type: organization
          type: job_template
      - identifier: Update Tf Task (Happy)
        related:
          success_nodes:
            - identifier: Sync Terraform Inventory
        extra_data:
          _hosts: localhost
          sn_manage_action: update
          sn_resource: sc_task
        inventory: Ansible-HCP Inventory
        unified_job_template:
          name: ServiceNow // Manage Resources
          organization:
            name: Autodotes
            type: organization
          type: job_template
      - identifier: Update Tf Task (Sad)
        extra_data:
          _hosts: localhost
          sn_manage_action: update
          sn_resource: sc_task
        inventory: Ansible-HCP Inventory
        unified_job_template:
          name: ServiceNow // Manage Resources
          organization:
            name: Autodotes
            type: organization
          type: job_template
      - identifier: Sync Terraform Inventory
        related:
          success_nodes:
            - identifier: Create Web Task
            - identifier: Create CIs
        unified_job_template:
          inventory:
            name: Ansible-HCP Inventory
            organization:
              name: Autodotes
              type: organization
            type: inventory
          name: app.terraform.io/zleblanc/azure-web-demo-dev/state
          type: inventory_source
      - identifier: Create CIs
        related:
          success_nodes:
            - identifier: Create Web Task
        extra_data:
          sn_manage_action: create
          sn_resource: ci
          sn_manage_multiple: true
        credentials:
          - name: AAP (id_rsa)
        inventory: Ansible-HCP Inventory
        unified_job_template:
          name: ServiceNow // Manage Resources
          organization:
            name: Autodotes
            type: organization
          type: job_template
      - identifier: Create Web Task
        all_parents_must_converge: true
        related:
          success_nodes:
            - identifier: Configure Web Servers
        credentials:
          - name: AAP (id_rsa)
        extra_data:
          _hosts: tag_demo_web
          sn_manage_action: create
          sn_resource: sc_task
        inventory: Ansible-HCP Inventory
        unified_job_template:
          name: ServiceNow // Manage Resources
          organization:
            name: Autodotes
            type: organization
          type: job_template
      - identifier: Configure Web Servers
        related:
          success_nodes:
            - identifier: Update Web Task (Happy)
            - identifier: Update RITM
          failure_nodes:
            - identifier: Update Web Task (Sad)
            - identifier: Terraform Destroy
        unified_job_template:
          name: Terraform // HCP // Azure Web Demo Configure
          organization:
            name: Autodotes
            type: organization
          type: job_template
      - identifier: Update Web Task (Happy)
        extra_data:
          _hosts: tag_demo_web
          sn_manage_action: update
          sn_resource: sc_task
        credentials:
          - name: AAP (id_rsa)
        inventory: Ansible-HCP Inventory
        unified_job_template:
          name: ServiceNow // Manage Resources
          organization:
            name: Autodotes
            type: organization
          type: job_template
      - identifier: Update RITM
        extra_data:
          _hosts: localhost
          sn_manage_action: update
          sn_resource: ritm
        inventory: Ansible-HCP Inventory
        unified_job_template:
          name: ServiceNow // Manage Resources
          organization:
            name: Autodotes
            type: organization
          type: job_template
      - identifier: Update Web Task (Sad)
        extra_data:
          _hosts: tag_demo_web
          sn_manage_action: update
          sn_resource: sc_task
        credentials:
          - name: AAP (id_rsa)
        inventory: Ansible-HCP Inventory
        unified_job_template:
          name: ServiceNow // Manage Resources
          organization:
            name: Autodotes
            type: organization
          type: job_template
      - identifier: Terraform Destroy
        job_tags: remove
        unified_job_template:
          name: Terraform // HCP // Azure Web Demo Deploy
          organization:
            name: Autodotes
            type: organization
          type: job_template
  - name: Terraform // GitHub // Azure Deploy and Configure Workflow
    organization: Autodotes
    labels:
      - Hashi
    ask_variables_on_launch: true
    ask_labels_on_launch: true
    workflow_nodes:
      - identifier: Sync Terraform Project
        related:
          success_nodes:
            - identifier: Terraform Run
        unified_job_template:
          name: Terraform Mgmt
          organization:
            name: Autodotes
            type: organization
          type: project
      - identifier: Terraform Run
        related:
          success_nodes:
            - identifier: Update CMDB
            - identifier: Sync Inventory
        unified_job_template:
          name: Terraform // GitHub // Azure Web Demo Deploy
          organization:
            name: Autodotes
            type: organization
          type: job_template
      - identifier: Update CMDB
        extra_data:
          sn_manage_action: create
          sn_resource: ci
          sn_manage_multiple: true
        inventory: Demo Inventory
        unified_job_template:
          name: ServiceNow // Manage Resources
          organization:
            name: Autodotes
            type: organization
          type: job_template
      - identifier: Sync Inventory
        related:
          success_nodes:
            - identifier: Configure Web Servers
        unified_job_template:
          inventory:
            name: Ansible-Terraform Inventory
            organization:
              name: Autodotes
              type: organization
            type: inventory
          name: Azure Open Environment
          type: inventory_source
      - identifier: Configure Web Servers
        unified_job_template:
          name: Terraform // GitHub // Azure Web Demo Configure
          organization:
            name: Autodotes
            type: organization
          type: job_template
  - name: Terraform // HCP // AWS Deploy and Configure Workflow
    organization: Autodotes
    labels:
      - Hashi
    survey_enabled: true
    survey_spec:
      name: workflow survey
      description: SSH public key passthrough
      spec:
        - question_name: SSH Public Key
          question_description: SSH public key which will enable configuration after provisioning
          max: 1024
          min: 0
          required: true
          type: password
          variable: aws_ssh_pubkey
        - question_name: Instance Type
          question_description: ec2 instance type
          max: 30
          min: 1
          required: true
          default: t3.small
          type: text
          variable: aws_ec2_instance_type
        - question_name: AWS Region
          question_description: aws region
          max: 30
          min: 1
          required: true
          default: us-east-1
          type: text
          variable: aws_region
    workflow_nodes:
      - identifier: Sync Project
        related:
          success_nodes:
            - identifier: Terraform Create
        unified_job_template:
          name: Terraform Mgmt
          organization:
            name: Autodotes
            type: organization
          type: project
      - identifier: Terraform Create
        related:
          failure_nodes:
            - identifier: Terraform Destroy
          success_nodes:
            - identifier: Sync Terraform Inventory
        unified_job_template:
          name: Terraform // HCP // AWS Web Demo Deploy
          organization:
            name: Autodotes
            type: organization
          type: job_template
      - identifier: Sync Terraform Inventory
        related:
          success_nodes:
            - identifier: Configure Web Servers
        unified_job_template:
          inventory:
            name: Ansible-HCP Inventory
            organization:
              name: Autodotes
              type: organization
            type: inventory
          name: app.terraform.io/zleblanc/aws-web-demo-dev/state
          type: inventory_source
      - identifier: Configure Web Servers
        related:
          failure_nodes:
            - identifier: Terraform Destroy
        unified_job_template:
          name: Terraform // HCP // AWS Web Demo Configure
          organization:
            name: Autodotes
            type: organization
          type: job_template
      - identifier: Terraform Destroy
        job_tags: remove
        unified_job_template:
          name: Terraform // HCP // AWS Web Demo Deploy
          organization:
            name: Autodotes
            type: organization
          type: job_template
