# ansible-playbook pb_aap_config.yml --tags aiops,credentials --skip-tags common
---
controller_credentials_aiops:
  - name: Ticket Enrichment API Key
    organization: Autodotes
    description: API key for the Ticket Enrichment LLM Subscription
    credential_type: OpenAI Config
    inputs:
      ai_rca_api_key: "{{ controller_credential_ai_rca_api_key }}"
      ai_rca_api_base: https://litellm-prod.apps.maas.redhatworkshops.io/v1
      ai_rca_model: Llama-Guard-3-1B
