# ansible-playbook pb_aap_config.yml -e "domains=aiops" -e "skip_common=true" --tags credentials
---
controller_credentials_aiops:
  - name: Lightwell Demo App Registry
    organization: Autodotes
    credential_type: Container Registry Auth File
    inputs:
      registry_host: quay.io
      registry_auth: "{{ controller_credential_lightwell_registry_auth }}"
  - name: Ticket Enrichment API Key
    organization: Autodotes
    description: API key for the Ticket Enrichment LLM Subscription
    credential_type: OpenAI Config
    inputs:
      ai_rca_api_key: "{{ controller_credential_ai_rca_api_key }}"
      ai_rca_api_base: https://litellm-prod.apps.maas.redhatworkshops.io/v1
      ai_rca_model: Llama-Guard-3-1B
