# ansible-playbook pb_aap_config.yml -e "domains=aiops" -e "skip_common=true" --tags event_stream
---
eda_event_streams_aiops:
  - name: DataDog Event Stream
    organization: Autodotes
    credential_name: DataDog Credential
    forward_events: true
  - name: DataDog OAuth Event Stream
    organization: Autodotes
    credential_name: Okta JWT Validator
    forward_events: true
  - name: Dynatrace Event Stream
    organization: Autodotes
    credential_name: Dynatrace Credential
    forward_events: true
  - name: ServiceNow Event Stream
    organization: Autodotes
    credential_name: ServiceNow Webhook Token
    forward_events: true
