# ansible-playbook pb_aap_config.yml --tags aiops,credential --skip-tags common
---
eda_credentials_aiops:
  - name: DataDog Credential
    organization: Autodotes
    description: integration with DataDog instance (mirarmax)
    credential_type: Token Event Stream
    inputs:
      auth_type: token
      token: "{{ eda_credential_datadog_token }}"
      http_header_key: Authorization
  - name: Decision Environment Container Registry
    organization: Autodotes
    description: redhat registry
    credential_type: Container Registry
    inputs:
      host: registry.redhat.io
      username: zachleblanc
      password: "{{ eda_credential_registry_redhat_zachleblanc }}"
      verify_ssl: true
  - name: Quay (zleblanc) Container Registry
    organization: Autodotes
    description: my quay registry (zleblanc)
    credential_type: Container Registry
    inputs:
      host: quay.io
      username: zleblanc
      password: "{{ eda_credential_registry_quay_zleblanc }}"
      verify_ssl: true
  - name: Dynatrace Credential
    organization: Autodotes
    description: integration with Dynatrace instance (ozi92582)
    credential_type: Token Event Stream
    inputs:
      auth_type: token
      token: "{{ eda_credential_dynatrace_token }}"
      http_header_key: Authorization
  - name: Demo Webhook Token
    organization: Autodotes
    description: integration with Demo Webhook
    credential_type: Token Event Stream
    inputs:
      auth_type: token
      token: "{{ eda_credential_demo_webhook_token }}"
      http_header_key: Authorization
  - name: ServiceNow Webhook Token
    organization: Autodotes
    description: integration with Service Now Business Rules
    credential_type: Token Event Stream
    inputs:
      auth_type: token
      token: "{{ eda_credential_servicenow_webhook_token }}"
      http_header_key: Authorization
  - name: OAuth2 Event Stream Client
    organization: Autodotes
    description: Example using an OAuth2 client credentials grant
    credential_type: OAuth2 Event Stream
    inputs:
      auth_type: oauth2
      client_id: "{{ eda_credential_oauth2_event_stream_client_id }}"
      client_secret: "{{ eda_credential_oauth2_event_stream_client_secret }}"
      introspection_url: "{{ eda_credential_oauth2_event_stream_introspect_url }}"
      http_header_key: Authorization
  - name: Autodotes Controller
    organization: Autodotes
    description: connect to Controller (autodotes.com)
    credential_type: Red Hat Ansible Automation Platform
    inputs:
      host: https://ansible.autodotes.com/api/controller/
      oauth_token: "{{ eda_credential_aap_token }}"
      verify_ssl: true
