# ansible-playbook pb_aap_config.yml -e "domains=aiops" -e "skip_common=true" --tags project
---
eda_projects_aiops:
  - name: EDA Demos
    description: A collection of various Event-Driven Ansible demos
    url: https://github.com/zjleblanc/ansible-eda-demos.git
    organization: Autodotes
