# ansible-playbook pb_aap_config.yml --tags aiops,job_templates --skip-tags common
---
controller_templates_aiops:
  - ask_variables_on_launch: true
    execution_environment: ee-default
    extra_vars:
      _hosts: localhost
      _msg: ran from aap
    inventory: Proxmox Inventory
    job_slice_count: 1
    job_type: run
    name: Demo Ansible Butler Clone
    labels: ["AIOps"]
    playbook: playbooks/no_op.yml
    project: Windows Mgmt
    survey_enabled: true
    survey_spec:
      description: ""
      name: ""
      spec:
        - choices: ""
          default: ""
          max: 1024
          min: 0
          new_question: true
          question_description: ""
          question_name: Specify target host(s)
          required: true
          type: text
          variable: _host
  - ask_variables_on_launch: true
    credentials:
      - AWS (ec2-user)
      - Dynatrace Demo Credential
      - West ServiceNow (ven07621)
    execution_environment: ee-default
    inventory: Cloud Inventory
    job_slice_count: 1
    job_type: run
    name: EDA // Dynatrace Problems
    labels: ["AIOps"]
    playbook: playbooks/resolve_problem.yml
    project: Event-Driven Demos
    use_fact_cache: true
  - ask_variables_on_launch: true
    credentials:
      - AAP (id_rsa)
      - Controller Credential
      - West ServiceNow (ven07621)
    execution_environment: ee-default
    inventory: Autodotes Lab
    job_slice_count: 1
    job_type: run
    name: EDA // Linux Remediation
    labels: ["AIOps"]
    playbook: demos/remediate_linux.yml
    project: Linux Mgmt
  - credentials:
      - AAP (id_rsa)
    execution_environment: ee-default
    inventory: Autodotes Lab
    job_slice_count: 1
    job_type: run
    name: EDA // Linux Remediation Setup
    labels: ["AIOps"]
    playbook: demos/remediate_setup.yml
    project: Linux Mgmt
    survey_enabled: true
    survey_spec:
      description: ""
      name: ""
      spec:
        - choices: ""
          default: rhel8
          max: 1024
          min: 0
          new_question: true
          question_description: inventory name of the target host (must be in Autodotes Lab Inventory)
          question_name: Specify target host(s)
          required: true
          type: text
          variable: _hosts
  - ask_variables_on_launch: true
    credentials:
      - Windows Server Credential
    execution_environment: ee-default
    extra_vars:
      _hosts: localhost
      _msg: ran from aap
    inventory: Proxmox Inventory
    job_slice_count: 1
    job_type: run
    name: EDA // No-Op
    labels: ["AIOps"]
    playbook: playbooks/no_op.yml
    project: Windows Mgmt
    survey_enabled: true
    survey_spec:
      description: ""
      name: ""
      spec:
        - choices: ""
          default: ""
          max: 1024
          min: 0
          new_question: false
          question_description: ""
          question_name: Specify target host(s)
          required: false
          type: text
          variable: _hosts
  - ask_variables_on_launch: true
    credentials:
      - AWS (ec2-user)
      - AWS Sandbox Credential
      - West ServiceNow (ven07621)
    execution_environment: ee-default
    inventory: Cloud Inventory
    job_slice_count: 1
    job_type: run
    name: EDA // OneAgent Restart
    labels: ["AIOps"]
    playbook: playbooks/remediate_onagent.yml
    project: Event-Driven Demos
  - ask_variables_on_launch: true
    credentials:
      - VMWare (ansible)
      - VMWare (gf7fr)
      - West ServiceNow (ven07621)
    execution_environment: ee-default
    extra_vars:
      kill_allowlist:
        - tail
        - cat
        - less
      threshold: 70
    inventory: Cloud Inventory
    job_slice_count: 1
    job_type: run
    name: EDA // Remediate High Memory Usage Processes
    labels: ["AIOps"]
    playbook: playbooks/remediate_memory_usage.yml
    project: Event-Driven Demos
  - name: AIOps // Ticket Enrichment // RHEL
    labels: ["Demo", "AIOps"]
    playbook: playbooks/aws/pb_ai_rca.yml
    project: Cloud Mgmt
    execution_environment: ee-default
    credentials:
      - AWS (ec2-user)
      - AWS Sandbox Credential
      - West ServiceNow (ven07621)
      - Ticket Enrichment API Key
    inventory: Cloud Inventory
    ask_variables_on_launch: true
  - ask_skip_tags_on_launch: true
    ask_variables_on_launch: true
    credentials:
      - AWS (ec2-user)
      - AWS Sandbox Credential
      - West ServiceNow (ven07621)
    execution_environment: ee-default
    inventory: Cloud Inventory
    job_slice_count: 1
    job_type: run
    name: EDA // Resize EBS Volume
    labels: ["AIOps"]
    playbook: playbooks/aws/add_disk_space.yml
    project: Cloud Mgmt
    survey_enabled: true
    survey_spec:
      description: ""
      name: ""
      spec:
        - choices: ""
          default: 120
          max: 1024
          min: 0
          new_question: true
          question_description: ""
          question_name: Max wait for reboot to complete (seconds)
          required: false
          type: integer
          variable: reboot_timeout
  - ask_variables_on_launch: true
    credentials:
      - AAP (id_rsa)
      - Controller Credential
      - West ServiceNow (ven07621)
    execution_environment: ee-default
    inventory: Autodotes Lab
    job_slice_count: 1
    job_type: run
    name: EDA // Rollback Demo Site Changes
    labels: ["AIOps"]
    playbook: playbooks/rollback_nginx_site.yml
    project: Event-Driven Demos
