# ansible-playbook pb_aap_config.yml -e "domains=aiops" -e "skip_common=true" --tags projects
---
controller_projects_aiops:
  - name: Event-Driven Demos
    organization: Autodotes
    scm_type: git
    scm_url: https://github.com/zjleblanc/ansible-eda-demos.git
