# ansible-playbook pb_aap_config.yml -e "domains=aiops" -e "skip_common=true" --tags projects
---
controller_projects_aiops:
  - name: Event-Driven Demos
    organization: Autodotes
    scm_type: git
    scm_url: https://github.com/zjleblanc/ansible-eda-demos.git
  - name: Lightwell Demo
    organization: Autodotes
    scm_type: git
    scm_url: https://github.com/zjleblanc/ansible-lightwell.git
    scm_refspec: "+refs/pull/*:refs/remotes/origin/pull/*"
    scm_update_on_launch: false # explicitly passed from EDA rulebook action
    allow_override: true
    default_environment: ee-default
