# ansible-playbook pb_aap_config.yml --tags aiops,projects --skip-tags common
---
controller_projects_aiops:
  - name: Event-Driven Demos
    organization: Autodotes
    scm_type: git
    scm_url: https://github.com/zjleblanc/ansible-eda-demos.git
