# ansible-playbook pb_aap_config.yml --tags cloud,credential_types --skip-tags common
---
controller_credential_types_cloud:
  - name: DataDog
    description: for integration with DataDog API
    kind: cloud
    inputs:
      fields:
        - id: datadog_site
          label: DataDog Site
          type: string
        - id: datadog_api_token
          label: DataDog API Token
          secret: true
          type: string
      required:
        - datadog_site
        - datadog_api_token
    injectors:
      env:
        DATADOG_API_TOKEN: !unsafe "{{ datadog_api_token }}"
        DATADOG_SITE: !unsafe "{{ datadog_site }}"
