# ansible-playbook pb_aap_config.yml --tags cloud,credentials --skip-tags common
---
controller_credentials_cloud:
  - name: DataDog Demo Credential
    organization: Autodotes
    description: integrate with DataDog API
    credential_type: DataDog
    inputs:
      datadog_api_token: "{{ controller_credential_datadog_api_token }}"
      datadog_site: "us5.datadoghq.com"
  - name: GCP Sandbox Credential
    organization: Autodotes
    description: GCP service account credential
    credential_type: Google Compute Engine
    inputs:
      username: "{{ controller_credential_gcp_service_acct_email }}"
      project: "{{ controller_credential_gcp_project }}"
      ssh_key_data: "{{ controller_credential_gcp_private_key }}"
  - name: Azure Key Vault Connection
    organization: Autodotes
    description: integration with azure key vault
    credential_type: Microsoft Azure Key Vault
    inputs:
      client: "{{ controller_credential_azure_client }}"
      cloud_name: AzureCloud
      secret: "{{ controller_credential_azure_secret }}"
      tenant: "{{ controller_credential_azure_tenant }}"
      url: https://zleblanc-ansible-kv.vault.azure.net
  - name: Gmail SMTP
    organization: Autodotes
    description: ""
    credential_type: SMTP Server
    inputs:
      email_smtp_from_address: ansible-autodotes@gmail.com
      email_smtp_password: "{{ controller_credential_email_smtp_password }}"
      email_smtp_server: smtp.gmail.com
      email_smtp_server_port: "587"
      email_smtp_username: zjleblanc3@gmail.com
  - name: Callback Plugin E-mail (zleblanc@redhat.com)
    organization: Autodotes
    description: Demo credential for sending e-mails in custom callback plugin
    credential_type: SMTP Callback
    inputs:
      email_smtp_from_address: zjleblanc3@gmail.com
      email_smtp_to_address: zleblanc@redhat.com
      email_smtp_password: "{{ controller_credential_email_smtp_password }}"
      email_smtp_server: smtp.gmail.com
      email_smtp_server_port: "587"
      email_smtp_username: zjleblanc3@gmail.com
