# ansible-playbook pb_aap_config.yml -e "domains=cloud" -e "skip_common=true" --tags inventories
---
controller_inventories_cloud:
  - name: Azure Inventory
    organization: Autodotes
    description: Demo using ARM inventory plugin
    labels:
      - Cloud
  - name: OpenFlake Inventory
    organization: Autodotes
    description: OpenFlake CMDB via servicenow.itsm.now inventory plugin
    labels:
      - Cloud
