# ansible-playbook pb_aap_config.yml -e "domains=cloud" -e "skip_common=true" --tags inventory_sources
---
controller_inventory_sources_cloud:
  - name: Minimal Sub
    description: ""
    inventory: Azure Inventory
    source: azure_rm
    source_project:
    source_path: ""
    source_vars:
    credential: Ansible Service Account (Minimal Sub)
    execution_environment:
    overwrite: false
    overwrite_vars: false
    update_on_launch: false
    update_cache_timeout: 0
    enabled_var: ""
    enabled_value: ""
    host_filter: ""
    limit: ""
    scm_branch: ""
    timeout: 0
    verbosity: 1
  - name: openflake.servicenow.itsm.now
    inventory: OpenFlake Inventory
    source: scm
    source_project: Cloud Mgmt
    source_path: inventories/snow/now.yml
    source_vars:
      target_env: test
    credential: OpenFlake
    execution_environment: ee-default
