# ansible-playbook pb_aap_config.yml --tags business,credentials --skip-tags common
---
controller_credentials_business:
  - name: Google OAuth Client (zleblanc-ansible)
    organization: Autodotes
    description: zleblanc-ansible-business OAuth2 client
    credential_type: Google OAuth Client
    inputs:
      google_client_id: 288513012227-3prbjvjmgknpje6spv6r3ml4ntrdo3jv.apps.googleusercontent.com
      google_client_secret: "{{ controller_credential_google_client_secret }}"
      google_refresh_token: "{{ controller_credential_google_refresh_token }}"
  - name: Account Task Summarizer API Key
    organization: Autodotes
    description: |-
      Ansible Task Summarizer key:
      https://maas-rhdp-frontend.apps.maas.redhatworkshops.io/api-keys
    credential_type: OpenAI Config
    inputs:
      ai_rca_api_key: "{{ controller_credential_ai_rca_api_key_bpa }}"
      ai_rca_api_base: https://maas-rhdp.apps.maas.redhatworkshops.io/v1
      ai_rca_model: deepseek-r1-distill-qwen-14b
