# ansible-playbook pb_aap_config.yml -e "domains=business" -e "skip_common=true" --tags projects
---
controller_projects_business:
  - name: Business Process
    organization: Autodotes
    scm_type: git
    scm_url: https://github.com/zjleblanc/ansible-business-process.git
    default_environment: ee-default
