# ansible-playbook pb_aap_config.yml -e "domains=hub" -e "skip_common=true" --tags registries
---
hub_ee_registries_hub:
  - name: quay_zleblanc
    url: https://quay.io
    username: zleblanc
    password: "{{ quay_password }}"
