# ansible-playbook pb_aap_config.yml --tags apps,credential_types --skip-tags common
---
controller_credential_types_apps:
  - name: Open Policy Agent Server
    description: for integration with Open Policy Agent Server
    kind: cloud
    inputs:
      fields:
        - id: opa_server
          label: Server URL
          help_text: http://localhost:8181
          type: string
        - id: opa_token
          label: Token
          secret: true
          type: string
        - id: opa_validate_certs
          label: Validate Certificates
          type: boolean
          default: true
      required:
        - opa_server
        - opa_token
        - opa_validate_certs
    injectors:
      extra_vars:
        opa_server: !unsafe "{{ opa_server }}"
        opa_token: !unsafe "{{ opa_token }}"
        opa_validate_certs: !unsafe "{{ opa_validate_certs }}"
  - name: Cloudflare Token
    description: "credential for integration with Cloudflare DNS"
    kind: cloud
    inputs:
      fields:
        - id: cloudflare_token
          label: API Token
          type: string
          secret: true
      required:
        - cloudflare_token
    injectors:
      env:
        CLOUDFLARE_TOKEN: !unsafe "{{ cloudflare_token }}"
  - name: CyberArk Conjur Client
    description: "credential for integration with CyberArk Conjur"
    kind: cloud
    inputs:
      fields:
        - id: conjur_account
          label: Account
          type: string
        - id: conjur_appliance_url
          label: Appliance URL
          type: string
        - id: conjur_login
          label: Login
          type: string
        - id: conjur_api_key
          label: API Key
          secret: true
          type: string
        - id: conjur_cert_file
          label: Conjur Certificate
          multiline: true
          type: string
      required:
        - conjur_account
        - conjur_appliance_url
        - conjur_login
        - conjur_api_key
        - conjur_cert_file
    injectors:
      env:
        CONJUR_ACCOUNT: !unsafe "{{ conjur_account }}"
        CONJUR_APPLIANCE_URL: !unsafe "{{ conjur_appliance_url }}"
        CONJUR_AUTHN_API_KEY: !unsafe "{{ conjur_api_key }}"
        CONJUR_AUTHN_LOGIN: !unsafe "{{ conjur_login }}"
        CONJUR_CERT_FILE: !unsafe "{{ tower.filename }}"
      file:
        template: !unsafe "{{ conjur_cert_file }}"
  - name: Demo CyberArk Conjur Secret
    description: ""
    kind: cloud
    inputs:
      fields:
        - id: raw_conjur_secret
          label: Encrypted Secret
          secret: true
          type: string
      required:
        - raw_conjur_secret
    injectors:
      extra_vars:
        conjur_secret: !unsafe "{{ raw_conjur_secret }}"
