# ansible-playbook pb_aap_config.yml --tags apps,credentials --skip-tags common
---
controller_credentials_apps:
  - name: OPA (local)
    organization: Autodotes
    credential_type: Open Policy Agent Server
    inputs:
      opa_server: "{{ controller_credential_opa_server }}"
      opa_token: "{{ controller_credential_opa_token }}"
      opa_validate_certs: false
  - name: Router
    organization: Autodotes
    description: SSH credential for connecting as zach user
    credential_type: Machine
    inputs:
      become_method: ""
      become_username: ""
      password: "{{ controller_credential_router_ssh_password }}"
      username: zach
  - name: Cloudflare DNS
    organization: Autodotes
    description: used to manage Cloudflare DNS records
    credential_type: Cloudflare Token
    inputs:
      cloudflare_token: "{{ controller_credential_cloudflare_token }}"
  - name: Conjur Credential
    organization: Autodotes
    description: used to lookup secrets from CyberArk Conjur
    credential_type: CyberArk Conjur Secrets Manager Lookup
    inputs:
      url: https://proxy:8443
      username: host/BotApp/Controller
      account: myConjurAccount
      api_key: REPLACE_ME
      cacert: REPLACE_ME
  - name: CyberArk Conjur Client (Controller)
    organization: Autodotes
    description: used to lookup secrets from CyberArk Conjur
    credential_type: CyberArk Conjur Client
    inputs:
      conjur_appliance_url: https://proxy:8443
      conjur_login: host/BotApp/Controller
      conjur_account: myConjurAccount
      conjur_api_key: REPLACE_ME
      conjur_cert_file: REPLACE_ME
  - name: CyberArk Conjur Secret - Ansible
    organization: Autodotes
    description: Used as conjur_secret
    credential_type: Demo CyberArk Conjur Secret
    inputs: {}
