# ansible-playbook pb_aap_config.yml --tags servicenow,job_templates --skip-tags common
---
controller_templates_servicenow:
  - name: Selenium // Automation Dashboard
    organization: Autodotes
    description: Demonstrate using Selenium to create application screen captures
    labels: ["Demo", "ServiceNow"]
    project: Cloud Mgmt
    playbook: demos/selenium_automation_dashboard.yml
    inventory: Autodotes Lab
    execution_environment: ee-selenium
    credentials:
      - AAP (id_rsa)
      - Ansible Vault
      - West ServiceNow (ven07621)
    extra_vars:
      _host: raspi
    survey_enabled: true
    survey_spec:
      name: ""
      description: ""
      spec:
        - question_name: Specify VMs to delete
          question_description: comma separated list of names (vm1,vm2)
          type: text
          default: demo-vm-1
          variable: aws_ec2_names_list
          required: true
  - name: Selenium // Screen Capture
    organization: Autodotes
    description: Demonstrate using Selenium to create application screen captures
    labels: ["Demo", "ServiceNow"]
    project: Cloud Mgmt
    playbook: demos/selenium_screen_capture.yml
    inventory: Autodotes Lab
    execution_environment: ee-selenium
    credentials:
      - AAP (id_rsa)
  - name: ServiceNow // Create CIs
    organization: Autodotes
    description: Create cmdb_ci_vm_instance items
    labels: ["Demo", "ServiceNow"]
    project: Cloud Mgmt
    playbook: playbooks/snow/manage_ci.yml
    inventory: Cloud Inventory
    execution_environment: ee-default
    credentials:
      - AWS (ec2-user)
      - West ServiceNow (ven07621)
    extra_vars:
      action: create
    survey_enabled: true
    survey_spec:
      description: ""
      name: ""
      spec:
        - max: 1024
          min: 1
          type: text
          default: OVERRIDE_ME
          required: true
          variable: _hosts
          question_name: Specify target host(s)
          question_description: pattern for the playbook hosts key
  - name: ServiceNow // Delete CIs
    organization: Autodotes
    description: Delete cmdb_ci_vm_instance items
    labels: ["Demo", "ServiceNow"]
    project: Cloud Mgmt
    playbook: playbooks/snow/manage_ci.yml
    inventory: Cloud Inventory
    execution_environment: ee-default
    credentials:
      - West ServiceNow (ven07621)
    extra_vars:
      action: delete
    survey_enabled: true
    survey_spec:
      description: ""
      name: ""
      spec:
        - max: 1024
          min: 1
          type: text
          default: OVERRIDE_ME
          required: true
          variable: _hosts
          question_name: Specify target host(s)
          question_description: pattern for the playbook hosts key
  - name: Service Now // Create Incident
    project: Cloud Mgmt
    playbook: playbooks/snow/create_incident.yml
    inventory: Autodotes Lab
    execution_environment: ee-default
    credentials:
      - West ServiceNow (ven07621)
    job_type: run
    job_slice_count: 1
  - name: Service Now // Mock Decomm VM
    project: Windows Mgmt
    playbook: demos/snow_no_op.yml
    inventory: Autodotes Lab
    execution_environment: ee-windows
    credentials:
      - West ServiceNow (ven07621)
    job_type: run
    job_slice_count: 1
    ask_variables_on_launch: true
  - name: Service Now // Update Incident
    project: Cloud Mgmt
    playbook: playbooks/snow/update_incident.yml
    inventory: Autodotes Lab
    credentials:
      - West ServiceNow (ven07621)
    job_type: run
    job_slice_count: 1
  - name: ServiceNow // Manage Resources
    organization: Autodotes
    description: Generic template to interface with supported ServiceNow Table API operations
    project: Cloud Mgmt
    playbook: playbooks/snow/manage_resource.yml
    execution_environment: ee-default
    credentials:
      - AAP (id_rsa)
      - West ServiceNow (ven07621)
    allow_simultaneous: true
    ask_variables_on_launch: true
    ask_inventory_on_launch: true
    ask_credential_on_launch: true
    extra_vars:
      sn_manage_action: REPLACE_ME # create, update, delete
      sn_resource: REPLACE_ME # sc_task, cr, ci
