# ansible-playbook pb_aap_config.yml --tags credential_types
---
controller_credential_types_common:
  - name: ServiceNow Credential
    description: Credential for use with servicenow.itsm collection
    kind: cloud
    injectors:
      env:
        SN_CLIENT_ID: !unsafe "{{ snow_client_id }}"
        SN_CLIENT_SECRET: !unsafe "{{ snow_client_secret }}"
        SN_HOST: !unsafe "{{ snow_host }}"
        SN_PASSWORD: !unsafe "{{ snow_password }}"
        SN_USERNAME: !unsafe "{{ snow_user }}"
    inputs:
      fields:
        - id: snow_host
          label: ServiceNow Host
          type: string
        - id: snow_user
          label: ServiceNow User
          type: string
        - id: snow_password
          label: ServiceNow User's Password
          secret: true
          type: string
        - id: snow_client_id
          label: ServiceNow Client Id
          type: string
        - id: snow_client_secret
          label: ServiceNow Client Secret
          secret: true
          type: string
      required:
        - snow_host
        - snow_user
        - snow_password
  - name: Dynatrace
    description: for integration with Dynatrace API
    kind: cloud
    injectors:
      env:
        DYNATRACE_API_TOKEN: !unsafe "{{ dynatrace_api_token }}"
        DT_API_TOKEN: !unsafe "{{ dynatrace_api_token }}"
        DYNATRACE_CLIENT_ID: !unsafe "{{ dynatrace_client_id }}"
        DYNATRACE_CLIENT_SECRET: !unsafe "{{ dynatrace_client_secret }}"
        DYNATRACE_HOST: !unsafe "{{ dynatrace_host }}"
    inputs:
      fields:
        - id: dynatrace_host
          label: Dynatrace Host
          type: string
        - id: dynatrace_client_id
          label: Dynatrace Client Id
          type: string
        - id: dynatrace_client_secret
          label: Dynatrace Client Secret
          secret: true
          type: string
        - id: dynatrace_api_token
          label: Dynatrace API Token
          secret: true
          type: string
      required:
        - dynatrace_host
  - name: Generic Token
    description: super generic token
    kind: cloud
    injectors:
      extra_vars:
        generic_token: !unsafe "{{ generic_token }}"
    inputs:
      fields:
        - id: generic_token
          label: Token
          secret: true
          type: string
      required:
        - token
  - name: Slack API Token
    description: Slack API Token Credential for leveraging workspace APIs
    kind: cloud
    injectors:
      extra_vars:
        slack_token: !unsafe "{{ raw_slack_token }}"
    inputs:
      fields:
        - id: raw_slack_token
          label: Encrypted Secret
          secret: true
          type: string
      required:
        - raw_slack_token
  - name: SMTP Callback
    description: For use with zjleblanc.utils callback plugins for sending e-mail notifications
    kind: cloud
    inputs:
      fields:
        - help_text: Example - smtp.gmail.com
          id: email_smtp_server
          label: Server
          type: string
        - help_text: Example - 587
          id: email_smtp_server_port
          label: Port
          type: string
        - help_text: Username to authenticate with SMTP server
          id: email_smtp_username
          label: Username
          type: string
        - help_text: Password to authenticate with SMTP server
          id: email_smtp_password
          label: Password
          secret: true
          type: string
        - help_text: Example - sender@gmail.com
          id: email_smtp_from_address
          label: From Address
          type: string
        - help_text: Example - recepient@gmail.com
          id: email_smtp_to_address
          label: To Address
          type: string
      required:
        - email_smtp_server
        - email_smtp_server_port
        - email_smtp_username
        - email_smtp_password
        - email_smtp_from_address
        - email_smtp_to_address
    injectors:
      env:
        SMTP_SERVER: !unsafe "{{ email_smtp_server }}"
        SMTP_PORT: !unsafe "{{ email_smtp_server_port }}"
        SMTP_USER: !unsafe "{{ email_smtp_username }}"
        SMTP_PASSWORD: !unsafe "{{ email_smtp_password }}"
        SMTP_EMAIL_FROM: !unsafe "{{ email_smtp_from_address }}"
        SMTP_EMAIL_TO: !unsafe "{{ email_smtp_to_address }}"
  - name: SMTP Server
    description: For use with community.general.mail module to send e-mail notifications
    kind: cloud
    injectors:
      extra_vars:
        MAILHOST: !unsafe "{{ email_smtp_server }}"
        MAILHOST_PASSWORD: !unsafe "{{ email_smtp_password }}"
        MAILHOST_PORT: !unsafe "{{ email_smtp_server_port }}"
        MAILHOST_USERNAME: !unsafe "{{ email_smtp_username }}"
        email_smtp_from_address: !unsafe "{{ email_smtp_from_address }}"
        email_smtp_password: !unsafe "{{ email_smtp_password }}"
        email_smtp_server: !unsafe "{{ email_smtp_server }}"
        email_smtp_server_port: !unsafe "{{ email_smtp_server_port }}"
        email_smtp_username: !unsafe "{{ email_smtp_username }}"
        smtp_password: !unsafe "{{ email_smtp_password }}"
        smtp_port: !unsafe "{{ email_smtp_server_port }}"
        smtp_username: !unsafe "{{ email_smtp_username }}"
        smtpserver: !unsafe "{{ email_smtp_server }}"
    inputs:
      fields:
        - help_text: Example - smtp.gmail.com
          id: email_smtp_server
          label: Server
          type: string
        - help_text: Example - 587
          id: email_smtp_server_port
          label: Port
          type: string
        - help_text: Username to authenticate with SMTP server
          id: email_smtp_username
          label: Username
          type: string
        - help_text: Password to authenticate with SMTP server
          id: email_smtp_password
          label: Password
          secret: true
          type: string
        - help_text: Example - sender@gmail.com
          id: email_smtp_from_address
          label: From Address
          type: string
      required:
        - email_smtp_server
        - email_smtp_server_port
        - email_smtp_username
        - email_smtp_password
  - name: SSH Proxy
    description: for connecting to a managed node through a bastion host
    kind: cloud
    injectors:
      env:
        SSH_PROXY_KEY: !unsafe "{{ tower.filename }}"
      extra_vars:
        ssh_proxy_host: !unsafe "{{ ssh_proxy_host }}"
        ssh_proxy_password: !unsafe "{{ ssh_proxy_password }}"
        ssh_proxy_username: !unsafe "{{ ssh_proxy_username }}"
      file:
        template: !unsafe "{{ ssh_proxy_key }}"
    inputs:
      fields:
        - id: ssh_proxy_username
          label: SSH Proxy Username
          type: string
        - id: ssh_proxy_password
          label: SSH Proxy Password
          secret: true
          type: string
        - id: ssh_proxy_host
          label: SSH Proxy Host
          type: string
        - format: ssh_private_key
          id: ssh_proxy_key
          label: SSH Proxy Private Key
          multiline: true
          secret: true
          type: string
      required:
        - ssh_proxy_username
        - ssh_proxy_host
