# ansible-playbook pb_aap_config.yml --tags credentials
---
controller_credentials_common:
  - name: Automation Hub RH Certified Repository
    organization: Autodotes
    description: Automation Hub RH Certified Repository
    credential_type: galaxy_api_token
    inputs:
      url: "https://ansible.autodotes.com/pulp_ansible/galaxy/rh-certified/"
      token: "{{ controller_credential_pah_galaxy_token }}"
  - name: AAP (awx)
    organization: Autodotes
    description: SSH credential for connecting as awx user
    credential_type: Machine
    inputs:
      become_method: ""
      become_username: ""
      ssh_key_data: "{{ controller_credential_ansible_ssh_key }}"
      username: awx
  - name: AAP (cloud-user)
    organization: Autodotes
    description: SSH credential for connecting as cloud-user user
    credential_type: Machine
    inputs:
      become_method: ""
      become_username: ""
      ssh_key_data: "{{ controller_credential_ansible_ssh_key }}"
      username: cloud-user
  - name: AAP (id_rsa)
    organization: Autodotes
    description: SSH credential for connecting as zach user
    credential_type: Machine
    inputs:
      become_method: ""
      become_username: ""
      ssh_key_data: "{{ controller_credential_ansible_ssh_key }}"
      username: zach
  - name: AAP (zach)
    organization: Autodotes
    description: SSH credential for connecting as zach user
    credential_type: Machine
    inputs:
      become_method: ""
      become_username: ""
      ssh_key_data: "{{ controller_credential_ansible_ssh_key }}"
      username: zach
  - name: AAP (root)
    description: SSH credential for connecting as root user
    organization: Autodotes
    credential_type: Machine
    inputs:
      become_method: ""
      become_username: ""
      ssh_key_data: "{{ controller_credential_ansible_ssh_key }}"
      username: root
  - name: Ansible Service Account (Minimal Sub)
    description: ansible-sa in zjleblanc3@gmail.com Azure Minimal Sub
    organization: Autodotes
    credential_type: Microsoft Azure Resource Manager
    inputs:
      client: "{{ controller_credential_azure_client }}"
      cloud_environment: ""
      secret: "{{ controller_credential_azure_secret }}"
      subscription: "{{ controller_credential_azure_subscription }}"
      tenant: "{{ controller_credential_azure_tenant }}"
      username: ""
  - name: Ansible Vault
    organization: Autodotes
    description: decrypt vaulted secret files
    credential_type: Vault
    inputs:
      vault_password: "{{ controller_credential_ansible_vault_password }}"
  - name: Automation Hub
    organization: Default
    description: Red Hat certified content
    credential_type: Ansible Galaxy/Automation Hub API Token
    inputs:
      auth_url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
      token: REPLACE_ME
      url: https://console.redhat.com/api/automation-hub/content/published/
  - name: Automation Hub Container Registry
    organization: Autodotes
    description: Private Automation Hub container registry
    credential_type: Container Registry
    inputs:
      host: ansible.autodotes.com
      password: "{{ controller_credential_container_registry_pah }}"
      username: admin
      verify_ssl: true
  - name: AWS (ec2-user)
    organization: Autodotes
    description: SSH credential for connecting as ec2-user user
    credential_type: Machine
    inputs:
      become_method: ""
      become_username: ""
      ssh_key_data: "{{ controller_credential_ansible_ssh_key }}"
      username: ec2-user
      password: "{{ controller_credential_ec2_password }}"
  - name: AWS Sandbox Credential
    organization: Autodotes
    description: AWS access/secret key combo
    credential_type: Amazon Web Services
    inputs:
      username: "{{ controller_credential_aws_access_key_id }}"
      password: "{{ controller_credential_aws_secret_key }}"
  - name: BitBucket (zleblancssa)
    organization: Autodotes
    credential_type: Source Control
    description: sync repositories from BitBucket
    inputs:
      ssh_key_data: "{{ controller_credential_ansible_ssh_key }}"
      username: zleblancssa
  - name: Controller Credential
    organization: Default
    credential_type: Red Hat Ansible Automation Platform
    description: used to integrate with the controller API
    inputs:
      host: https://ansible.autodotes.com
      oauth_token: "{{ controller_credential_aap25_token }}"
      username: ""
      verify_ssl: false
  - name: Dynatrace Demo Credential
    organization: Autodotes
    credential_type: Dynatrace
    description: integrate with Dynatrace API
    inputs:
      dynatrace_api_token: "{{ controller_credential_dynatrace_api_token }}"
      dynatrace_client_id: ""
      dynatrace_host: https://ozi92582.live.dynatrace.com
  - name: Gitlab - Autodotes
    description: SSH key for GitLab auth
    organization: Autodotes
    credential_type: Source Control
    inputs:
      password: NOT_USED
      ssh_key_data: "{{ controller_credential_gitlab_ssh_key }}"
      username: zjleblanc
  - name: VMWare (ansible)
    description: ""
    organization: Autodotes
    credential_type: Machine
    inputs:
      become_method: ""
      become_username: ""
      ssh_key_data: "{{ controller_credential_ansible_ssh_key }}"
      username: ansible
  - name: VMWare Bastion (gf7fr)
    description: bastion host for VMWare sandbox env
    organization: Autodotes
    credential_type: SSH Proxy
    inputs:
      ssh_proxy_host: bastion-gf7fr.gf7fr.dynamic.redhatworkshops.io
      ssh_proxy_key: "{{ controller_credential_ansible_ssh_key }}"
      ssh_proxy_password: "{{ controller_credential_vmware_bastion }}"
      ssh_proxy_username: lab-user
  - name: VMWare (gf7fr)
    description: credential for vCenter API
    organization: Autodotes
    credential_type: VMware vCenter
    inputs:
      host: vcsnsx-vc.infra.demo.redhat.com
      password: "{{ controller_credential_vmware_vcenter }}"
      username: sandbox-gf7fr@demo
  - name: West ServiceNow (ven07621)
    description: for integrating with ServiceNow using servicenow.itsm collection
    organization: Autodotes
    credential_type: ServiceNow Credential
    inputs:
      snow_client_id: ""
      snow_host: https://ven07621.service-now.com/
      snow_password: "{{ controller_credential_servicenow_ven07621 }}"
      snow_user: zleblanc
  - name: Windows Server Credential
    description: ""
    organization: Autodotes
    credential_type: Machine
    inputs:
      become_method: ""
      become_username: ""
      password: "{{ controller_credential_windows_domain_admin_password }}"
      username: Administrator
