# ansible-playbook pb_aap_config.yml -e "domains=aap" -e "skip_common=true" --tags credential_types
---
controller_credential_types_aap:
  - name: EE Build Credential
    description: for automation the execution environment build process
    kind: cloud
    inputs:
      fields:
        - id: base_registry_username
          label: RH registry Username
          type: string
        - id: base_registry_password
          label: RH registry Password
          secret: true
          type: string
        - id: ee_registry_username
          label: AH registry Username
          type: string
        - id: ee_registry_password
          label: AH registry Password
          secret: true
          type: string
        - id: ee_ah_host
          label: AH Hostname
          type: string
        - id: ee_ah_token
          label: AH Token
          secret: true
          type: string
        - default: false
          id: ee_validate_certs
          label: Validate certs
          type: boolean
      required:
        - base_registry_username
        - base_registry_password
    injectors:
      extra_vars:
        ah_host: !unsafe "{{ ee_ah_host }}"
        ah_token: !unsafe "{{ ee_ah_token }}"
        ee_base_registry_password: !unsafe "{{ base_registry_password }}"
        ee_base_registry_username: !unsafe "{{ base_registry_username }}"
        ee_registry_password: !unsafe "{{ ee_registry_password }}"
        ee_registry_username: !unsafe "{{ ee_registry_username }}"
        ee_validate_certs: !unsafe "{{ ee_validate_certs }}"
  - name: EE Utilities
    description: for use with the execution environment utilities collection
    kind: cloud
    inputs:
      fields:
        - id: ee_base_reg_user
          label: Base Registry Username
          type: string
        - id: ee_base_reg_password
          label: Base Registry Password
          secret: true
          type: string
        - help_text: "ex: quay.io/zleblanc"
          id: ee_dest_reg
          label: Destination Registry
          type: string
        - id: ee_dest_reg_user
          label: Destination Registry Username
          type: string
        - id: ee_dest_reg_password
          label: Destination Registry Password
          secret: true
          type: string
      required:
        - ee_base_reg_user
        - ee_base_reg_password
        - ee_dest_reg
        - ee_dest_reg_user
        - ee_dest_reg_password
    injectors:
      extra_vars:
        ee_base_reg_password: !unsafe "{{ ee_base_reg_password }}"
        ee_base_reg_user: !unsafe "{{ ee_base_reg_user }}"
        ee_dest_reg: !unsafe "{{ ee_dest_reg }}"
        ee_dest_reg_password: !unsafe "{{ ee_dest_reg_password }}"
        ee_dest_reg_user: !unsafe "{{ ee_dest_reg_user }}"
  - name: Private Automation Hub
    description: For integration with the PAH API via ansible.hub collection
    kind: cloud
    inputs:
      fields:
        - id: pah_host
          label: Host
          type: string
        - id: pah_username
          label: Username
          type: string
        - id: pah_password
          label: Password
          secret: true
          type: string
        - id: pah_token
          label: Token
          secret: true
          type: string
        - id: pah_verify_ssl
          label: Verify SSL?
          type: boolean
      required:
        - pah_host
    injectors:
      env:
        AH_API_TOKEN: !unsafe "{{ pah_token }}"
        AH_HOST: !unsafe "{{ pah_host }}"
        AH_PASSWORD: !unsafe "{{ pah_password }}"
        AH_USERNAME: !unsafe "{{ pah_username }}"
        AH_VERIFY_SSL: !unsafe "{{ pah_verify_ssl }}"
        PAH_HOST: !unsafe "{{ pah_host }}"
        PAH_PASSWORD: !unsafe "{{ pah_password }}"
        PAH_TOKEN: !unsafe "{{ pah_token }}"
        PAH_USERNAME: !unsafe "{{ pah_username }}"
        PAH_VERIFY_SSL: !unsafe "{{ pah_verify_ssl }}"
