---
controller_execution_environments:
  - name: ee-default
    description: my default execution environment with all the collections and libraries \
    image: quay.io/zleblanc/ee-default:87a71cbb
  - name: ee-windows
    description: my windows execution environment including kerberos conf
    image: quay.io/zleblanc/ee-windows:8f5cb8c00edcb1c2d7b74c1c59aaf0d787a098bf
  - name: ee-networking
    description: my networking execution environment
    image: quay.io/zleblanc/ee-networking:7311e0e
  - name: ee-selenium
    description: Used to demonstrate automated screen captures using selenium and chrome
    image: quay.io/zleblanc/ee-selenium:v4
  - name: ee-cloud
    description: Scott Harwell's Cloud EE hosted in quay
    image: quay.io/scottharwell/cloud-ee
  - name: product-demos-ee
    description: Ansible Product Demos EE
    image: quay.io/acme_corp/product-demos-ee:be37a30ae707621916178f87512be6b3306a94d4

