# ansible-playbook pb_aap_config.yml --tags windows,credentials --skip-tags common
---
controller_credentials_windows:
  - name: Autodotes AD LDAP Credential
    organization: Autodotes
    description: connect to Autodotes Active Directory domain controller
    credential_type: MSFT AD LDAP Demo
    inputs:
      ldap_ca_cert: ""
      ldap_cert_validation: ignore
      ldap_certificate: ""
      ldap_certificate_key: ""
      ldap_password: "{{ controller_credential_domain_controller_password }}"
      ldap_port: "389"
      ldap_server: 192.168.0.66
      ldap_username: zach@autodotes.local
  - name: Autodotes[com] Admin
    organization: Autodotes
    description: Autodotes Active Directory domain administrator
    credential_type: Windows Domain Administrator
    inputs:
      admin_account: Administrator
      admin_password: "{{ controller_credential_windows_domain_admin_password }}"
      domain: autodotes.com
  - name: Autodotes[local] Admin
    organization: Autodotes
    description: autodotes.local domain admin account
    credential_type: Windows Domain Administrator
    inputs:
      admin_account: zach
      admin_password: "{{ controller_credential_windows_domain_zach_password }}"
      domain: autodotes.local
  - name: Demo SQL Service Account Credentials
    organization: Autodotes
    credential_type: SQL Server Service Accounts
    description: used for deploy mssql and configuring service accounts
    inputs:
      mssql_agentsvc_account: AUTODOTES\sql_agt
      mssql_agentsvc_account_pass: "{{ controller_credential_mssql_agentsvc_account_pass }}"
      mssql_assvc_account: AUTODOTES\sql_svc
      mssql_assvc_account_pass: "{{ controller_credential_mssql_assvc_account_pass }}"
      mssql_sqlsvc_account: AUTODOTES\sql_svc
      mssql_sqlsvc_account_pass: "{{ controller_credential_mssql_sqlsvc_account_pass }}"
  - name: Proxmox API
    description: ""
    organization: Autodotes
    credential_type: Proxmox VE Credential
    inputs:
      pve_api_host: nuc.autodotes.com
      pve_api_port: "8006"
      pve_api_token_id: postman
      pve_api_token_secret: "{{ controller_credential_pve_token_postman }}"
      pve_api_user: root@pam
  - name: Proxmox Windows Default Credential
    description: ""
    organization: Autodotes
    credential_type: Promox User Credential
    inputs:
      pve_user: Administrator
      pve_user_password: "{{ controller_credential_windows_domain_admin_password }}"
  - name: Windows Kerberos Credential
    description: ""
    organization: Autodotes
    credential_type: Machine
    inputs:
      become_method: ""
      become_username: ""
      password: "{{ controller_credential_windows_domain_zach_password }}"
      username: zach@AUTODOTES.COM
