# ansible-playbook pb_aap_config.yml --tags windows,credential_types --skip-tags common
---
controller_credential_types_windows:
  - name: Kerberos
    description: Credential to inject krb5 conf and supply username/password for generating a ticket
    kind: cloud
    inputs:
      fields:
        - id: username
          type: string
          label: Username
        - id: password
          type: string
          label: Password
          secret: true
        - id: default_realm
          type: string
          label: Default Realm
        - id: kdc
          type: string
          label: KDC
          help_text: Optional KDC, use only if KDC DNS lookup not working
      required:
        - username
        - password
        - default_realm
    injectors:
      env:
        KRB5_CONFIG: !unsafe "{{ tower.filename }}"
      file:
        template: !unsafe |-
          [libdefaults]
          default_realm = {{ default_realm | upper }}
          dns_canonicalize_hostname = fallback
          dns_lookup_kdc = {% if kdc %}false{% else %}true{% endif %}
          dns_lookup_realm = true
          forwardable = true
          rdns = false
          #udp_preference_limit = 1
          [realms]
          {{ default_realm | upper }} = {
            {% if kdc %}kdc = {{ kdc }}{% endif %}
          }
          [domain_realm]
            {{ default_realm | lower }} = {{ default_realm | upper }}
      extra_vars:
        ansible_user: !unsafe "{{ username }}"
        ansible_password: !unsafe "{{ password }}"
  - name: MSFT AD LDAP Demo
    description: for integrating with an Active Directory server
    kind: cloud
    inputs:
      fields:
        - help_text: The domain controller/server to connect to
          id: ldap_server
          label: LDAP Server
          type: string
        - help_text: Port 389 is used for LDAP and port 686 is used for LDAPS
          id: ldap_port
          label: LDAP Port
          type: string
        - id: ldap_username
          label: LDAP Username
          type: string
        - id: ldap_password
          label: LDAP Password
          secret: true
          type: string
        - choices:
            - simple
            - certificate
            - kerberos
            - negotiate
            - ntlm
          id: ldap_auth_protocol
          label: LDAP Auth Protocol
          type: string
        - choices:
            - always
            - ignore
            - ignore_hostname
          help_text: The certificate validation behaviour when using a TLS connection
          id: ldap_cert_validation
          label: LDAP Cert Validation
          type: string
        - help_text: Can be the path to a CA certificate PEM or DER file, directory of PEM certificates, or the CA certificate PEM string that is used for certificate validation
          id: ldap_ca_cert
          label: LDAP CA Cert
          type: string
        - help_text: The value can either be a path to a file containing the certificate or string of the PEM encoded certificate
          id: ldap_certificate
          label: LDAP Certificate
          type: string
        - help_text: The value can either be a path to a file containing the key in the PEM or DER encoded form, or it can be the string of a PEM encoded key
          id: ldap_certificate_key
          label: LDAP Certificate Key
          type: string
        - help_text: The password used to decrypt the certificate key specified by LDAP Certificate or LDAP Certificate Key
          id: ldap_certificate_password
          label: LDAP Certificate Password
          secret: true
          type: string
      required:
        - ldap_server
    injectors:
      env:
        MICROSOFT_AD_LDAP_AUTH_PROTOCOL: !unsafe "{{ ldap_auth_protocol | default('negotiate', true) }}"
        MICROSOFT_AD_LDAP_CA_CERT: !unsafe "{{ ldap_ca_cert }}"
        MICROSOFT_AD_LDAP_CERTIFICATE: !unsafe "{{ ldap_certificate }}"
        MICROSOFT_AD_LDAP_CERTIFICATE_KEY: !unsafe "{{ ldap_certificate_key }}"
        MICROSOFT_AD_LDAP_CERTIFICATE_PASSWORD: !unsafe "{{ ldap_certificate_password }}"
        MICROSOFT_AD_LDAP_CERT_VALIDATION: !unsafe "{{ ldap_cert_validation }}"
        MICROSOFT_AD_LDAP_PASSWORD: !unsafe "{{ ldap_password }}"
        MICROSOFT_AD_LDAP_PORT: !unsafe "{{ ldap_port | default('389') }}"
        MICROSOFT_AD_LDAP_SERVER: !unsafe "{{ ldap_server }}"
        MICROSOFT_AD_LDAP_USERNAME: !unsafe "{{ ldap_username }}"
  - name: Promox User Credential
    description: Default creds for a Proxmox instance
    kind: cloud
    inputs:
      fields:
        - id: pve_user
          label: PVE Instance User
          type: string
        - id: pve_user_password
          label: PVE Instance User's Password
          secret: true
          type: string
      required:
        - pve_user
        - pve_user_password
    injectors:
      extra_vars:
        proxmox_default_password: !unsafe "{{ pve_user_password }}"
        proxmox_default_user: !unsafe "{{ pve_user }}"
  - name: Proxmox VE Credential
    description: Authenticate with a Proxmox VE API
    kind: cloud
    inputs:
      fields:
        - id: pve_api_host
          label: Host
          type: string
        - id: pve_api_port
          label: Port
          type: string
        - id: pve_api_user
          label: User
          type: string
        - id: pve_api_token_id
          label: Token Id
          type: string
        - id: pve_api_token_secret
          label: Token Secret
          secret: true
          type: string
        - id: pve_api_password
          label: Password
          secret: true
          type: string
      required:
        - pve_api_host
        - pve_api_user
    injectors:
      env:
        PROXMOX_HOST: !unsafe "{{ pve_api_host }}"
        PROXMOX_PASSWORD: !unsafe "{{ pve_api_password }}"
        PROXMOX_PORT: !unsafe "{{ pve_api_port }}"
        PROXMOX_USER: !unsafe "{{ pve_api_user }}"
      extra_vars:
        proxmox_api_host: !unsafe "{{ pve_api_host }}"
        proxmox_api_password: !unsafe "{{ pve_api_password }}"
        proxmox_api_token_id: !unsafe "{{ pve_api_token_id }}"
        proxmox_api_token_secret: !unsafe "{{ pve_api_token_secret }}"
        proxmox_api_user: !unsafe "{{ pve_api_user }}"
        pve_api_port: !unsafe "{{ pve_api_port }}"
  - name: SQL Server Service Accounts
    description: To connect and run queries against a SQL Server instance
    kind: cloud
    inputs:
      fields:
        - id: mssql_sqlsvc_account
          label: SQL Service Account
          type: string
        - id: mssql_sqlsvc_account_pass
          label: SQL Service Account Password
          secret: true
          type: string
        - id: mssql_agentsvc_account
          label: SQL Agent Account
          type: string
        - id: mssql_agentsvc_account_pass
          label: SQL Agent Account Password
          secret: true
          type: string
        - id: mssql_assvc_account
          label: SQL Analysis Services Account
          type: string
        - id: mssql_assvc_account_pass
          label: SQL Analysis Services Account Password
          secret: true
          type: string
      required:
        - mssql_sqlsvc_account
        - mssql_sqlsvc_account_pass
        - mssql_agentsvc_account
        - mssql_agentsvc_account_pass
        - mssql_assvc_account
        - mssql_assvc_account_pass
    injectors:
      extra_vars:
        mssql_agentsvc_account: !unsafe "{{ mssql_agentsvc_account }}"
        mssql_agentsvc_account_pass: !unsafe "{{ mssql_agentsvc_account_pass }}"
        mssql_assvc_account: !unsafe "{{ mssql_assvc_account }}"
        mssql_assvc_account_pass: !unsafe "{{ mssql_assvc_account_pass }}"
        mssql_sqlsvc_account: !unsafe "{{ mssql_sqlsvc_account }}"
        mssql_sqlsvc_account_pass: !unsafe "{{ mssql_sqlsvc_account_pass }}"
  - name: Windows Domain Administrator
    description: Credentials for a windows domain administrator
    kind: cloud
    inputs:
      fields:
        - id: domain
          label: Domain Name
          type: string
        - id: admin_account
          label: Administrator Account
          type: string
        - id: admin_password
          label: Administrator Password
          secret: true
          type: string
      required:
        - domain
        - admin_account
        - admin_password
    injectors:
      extra_vars:
        win_domain: !unsafe "{{ domain }}"
        win_domain_admin: !unsafe "{{ admin_account }}"
        win_domain_admin_password: !unsafe "{{ admin_password }}"
