# ansible-playbook pb_aap_config.yml -e "domains=windows" -e "skip_common=true" --tags inventories
---
controller_inventories_windows:
  - name: Windows Inventory
    organization: Autodotes
    description: Isolates Windows hosts in AWS
    labels:
      - Windows
    variables:
      ansible_connection: winrm
      ansible_winrm_port: 5986
      ansible_winrm_server_cert_validation: ignore
      ansible_winrm_kerberos_delegation: true
      aws_region: east-us-2
