# ansible-playbook pb_aap_config.yml --tags windows,inventory_sources --skip-tags common
---
controller_inventory_sources_windows:
  - name: Windows EC2 Instances
    description: ""
    inventory: Windows Inventory
    source: ec2
    source_project:
    source_path: ""
    source_vars:
      aws_region: us-east-2
      compose:
        ansible_platform: platform
      filters:
        tag:role:
          - domain_controller
          - domain_computer
      hostnames:
        - tag:Name
      keyed_groups:
        - key: tags['role']
          prefix: role
    credential: AWS Sandbox Credential
    execution_environment: ee-default
    overwrite: true
    overwrite_vars: true
    update_on_launch: false
    update_cache_timeout: 0
    enabled_var: ""
    enabled_value: ""
    host_filter: ""
    limit: ""
    scm_branch: ""
    timeout: 0
    verbosity: 1
