# ansible-playbook pb_aap_config.yml --tags windows,job_templates --skip-tags common
---
controller_templates_windows:
  - ask_variables_on_launch: true
    credentials:
      - West ServiceNow (ven07621)
      - Windows Kerberos Credential
    execution_environment: ee-windows
    extra_vars:
      kvm_name: hcl-guest-1
      sys_id: undef
    inventory: Workshop Inventory
    job_slice_count: 1
    job_type: run
    name: Proxmox // Decomm VM
    playbook: demos/decomm_kvm.yml
    project: Windows Mgmt
    skip_tags: dns_delete,kvm_delete,ad_delete
  - ask_variables_on_launch: true
    credentials:
      - Proxmox API
    execution_environment: ee-default
    inventory: Autodotes Lab
    job_slice_count: 1
    job_type: run
    name: Proxmox // Manage Instance State
    playbook: playbooks/proxmox_vm_state.yml
    project: Linux Mgmt
  - ask_skip_tags_on_launch: true
    ask_variables_on_launch: true
    credentials:
      - Autodotes[local] Admin
      - West ServiceNow (ven07621)
      - Windows Kerberos Credential
    execution_environment: ee-windows
    inventory: Proxmox Inventory
    job_slice_count: 1
    job_type: run
    name: Proxmox // Prep VM for Decomm
    playbook: demos/decomm_kvm_prep.yml
    project: Windows Mgmt
    skip_tags: kvm_snapshot,ad_disable,kvm_stop
  - ask_variables_on_launch: true
    credentials:
      - AAP (root)
    description: Create a proxmox kvm guest
    execution_environment: ee-default
    extra_vars:
      proxmox_vm_configs:
        - cores: 2
          cpu: host
          description: KVM guest created from template
          ide:
            ide2: none,media=cdrom
          kvm: !unsafe "{{ qcows.rhel7 }}"
          memory: 8192
          name: rhel-guest-1
          net:
            net0: virtio,bridge=vmbr0,firewall=1
          node: pve
          onboot: true
          ostype: l26
          scsihw: virtio-scsi-single
          sockets: 2
          tags:
            - demo
            - rhel
            - linux
          timeout: 120
          virtio:
            virtio0: local:32,format=qcow2
      qcows:
        rhel7: rhel-server-7.9-x86_64-kvm.qcow2
        rhel8: rhel-8.7-x86_64-kvm.qcow2
        rhel9: rhel-baseos-9.1-x86_64-kvm.qcow2
    inventory: Proxmox Inventory
    job_slice_count: 1
    job_type: run
    name: Proxmox // Provision KVM Guest
    playbook: demos/proxmox_kvm_guest.yml
    project: Linux Mgmt
  - ask_variables_on_launch: true
    credentials:
      - Controller Credential
      - Proxmox Windows Default Credential
    description: Provision a VM in Proxmox VE
    execution_environment: ee-windows
    extra_vars:
      proxmox_ve_configs:
        - agent: true
          clone: win11-admin-server-template
          full: false
          name: win11-guest-1
          nameservers:
            - 8.8.8.8
          node: pve
          tags:
            - ansible
            - windows
            - yaml-config
    inventory: Proxmox Inventory
    job_slice_count: 1
    job_type: run
    name: Proxmox // Provision Windows VM
    playbook: demos/proxmox_kvm_clone.yml
    project: Windows Mgmt
    survey_spec:
      description: ""
      name: ""
      spec:
        - choices: ""
          default: ""
          max: 100
          min: 0
          new_question: false
          question_description: ""
          question_name: What is the VM name? (for proxmox UI)
          required: true
          type: text
          variable: pve_survey_name
        - choices:
            - win11-server-template
          default: win11-server-template
          max: 1024
          min: 0
          new_question: false
          question_description: ""
          question_name: What template are you cloning?
          required: true
          type: multiplechoice
          variable: pve_survey_clone
        - choices:
            - pve
          default: pve
          max: 1024
          min: 0
          new_question: false
          question_description: ""
          question_name: What proxmox node?
          required: true
          type: multiplechoice
          variable: pve_survey_node
        - choices: ""
          default: ansible-created,windows
          max: 1024
          min: 0
          new_question: false
          question_description: ""
          question_name: Provide VM tags (comma separated)
          required: false
          type: text
          variable: pve_survey_tags
        - choices:
            - 1.1.1.1
            - 8.8.8.8
            - 192.168.1.1
          default: 8.8.8.8
          max: 1024
          min: 0
          new_question: false
          question_description: ""
          question_name: Select your nameservers
          required: false
          type: multiselect
          variable: pve_survey_nameservers
        - choices:
            - "yes"
            - "no"
          default: "no"
          max: 1024
          min: 0
          new_question: false
          question_description: ""
          question_name: Are you doing a full clone?
          required: false
          type: multiplechoice
          variable: pve_survey_full
        - choices:
            - "2"
            - "4"
            - "8"
          default: "2"
          max: 1024
          min: 0
          new_question: false
          question_description: ""
          question_name: How many cores?
          required: false
          type: multiplechoice
          variable: pve_survey_cores
        - choices: ""
          default: 4096
          max: 8192
          min: 0
          new_question: false
          question_description: ""
          question_name: How much memory? (in MB)
          required: false
          type: integer
          variable: pve_survey_memory
        - choices: ""
          default: 1200
          max: 3600
          min: 0
          new_question: false
          question_description: ""
          question_name: Set provisioning timeout (in seconds)
          required: false
          type: integer
          variable: pve_survey_timeout
    verbosity: 3
  - credentials:
      - Controller Credential
      - Proxmox Windows Default Credential
    execution_environment: ee-windows
    inventory: Proxmox Inventory
    job_slice_count: 1
    job_type: run
    name: Proxmox // Setup WinRM
    playbook: demos/setup_winrm.yml
    project: Windows Mgmt
  - credentials:
      - Autodotes[local] Admin
    execution_environment: ee-windows
    inventory: Proxmox Inventory
    job_slice_count: 1
    job_type: run
    name: Windows // Bulk Add Users to Group
    playbook: demos/bulk_add_users_to_group.yml
    project: Windows Mgmt
    survey_enabled: true
    survey_spec:
      description: ""
      name: ""
      spec:
        - choices: ""
          default: DC=autodotes,DC=local
          max: 1024
          min: 0
          new_question: true
          question_description: ""
          question_name: Enter a subtree to search
          required: true
          type: text
          variable: search_root
        - choices: ""
          default: Austin
          max: 1024
          min: 0
          new_question: true
          question_description: ""
          question_name: Enter your target group name
          required: true
          type: text
          variable: target_group
        - choices: ""
          default: "example_user1\nexample_user2"
          max: 102400
          min: 0
          new_question: true
          question_description: ""
          question_name: Paste in your list of user accounts
          required: true
          type: textarea
          variable: user_accounts
  - credentials:
      - Ansible Vault
    execution_environment: ee-windows
    inventory: Windows Inventory
    job_slice_count: 1
    job_type: run
    name: Windows // EC2 Domain Configure
    playbook: demos/ad_domain/pb_domain_config.yml
    project: Windows Mgmt
  - credentials:
      - Ansible Vault
      - AWS Sandbox Credential
    execution_environment: ee-default
    inventory: Windows Inventory
    job_slice_count: 1
    job_type: run
    name: Windows // EC2 Domain Infra Deploy
    playbook: demos/ad_domain/pb_aws_infra.yml
    project: Windows Mgmt
  - credentials:
      - Ansible Vault
    execution_environment: ee-windows
    inventory: Windows Inventory
    job_slice_count: 1
    job_type: run
    name: Windows // EC2 Domain Join
    playbook: demos/ad_domain/pb_domain_join.yml
    project: Windows Mgmt
  - credentials:
      - Ansible Vault
      - AWS Sandbox Credential
    execution_environment: ee-windows
    inventory: Windows Inventory
    job_slice_count: 1
    job_type: run
    name: Windows // EC2 Domain Setup [Monolith]
    playbook: demos/ad_domain/setup.yml
    project: Windows Mgmt
  - ask_verbosity_on_launch: true
    credentials:
      - Windows Kerberos Credential
    execution_environment: ee-windows
    inventory: Windows Inventory
    job_slice_count: 1
    job_type: run
    name: Windows // EC2 Kerberos Check
    playbook: demos/ad_domain/pb_check_krb.yml
    project: Windows Mgmt
  - ask_credential_on_launch: true
    ask_inventory_on_launch: true
    ask_limit_on_launch: true
    ask_variables_on_launch: true
    credentials:
      - Windows Server Credential
    execution_environment: ee-windows
    inventory: Proxmox Inventory
    job_slice_count: 1
    job_type: run
    name: Windows // Gather Facts
    playbook: playbooks/win_facts.yml
    project: Windows Mgmt
    use_fact_cache: true
  - ask_variables_on_launch: true
    credentials:
      - Windows Kerberos Credential
    execution_environment: ee-windows
    extra_vars:
      domain_controller: dc01.autodotes.com
      servers: "winston\nwinthrop"
    inventory: Windows Inventory
    job_slice_count: 1
    job_type: run
    name: Windows // Get Folder Stats
    playbook: playbooks/get_folder_stats.yml
    project: Windows Mgmt
  - ask_limit_on_launch: true
    credentials:
      - Autodotes[local] Admin
      - Controller Credential
      - Windows Server Credential
    execution_environment: ee-windows
    extra_vars:
      join_domain: true
    inventory: Proxmox Inventory
    job_slice_count: 1
    job_type: run
    limit: windows
    name: Windows // Join Domain
    playbook: demos/join_domain.yml
    project: Windows Mgmt
  - ask_limit_on_launch: true
    credentials:
      - Autodotes[local] Admin
      - Controller Credential
      - Windows Server Credential
    execution_environment: ee-windows
    inventory: Proxmox Inventory
    job_slice_count: 1
    job_type: run
    name: Windows // Leave Domain
    playbook: demos/leave_domain.yml
    project: Windows Mgmt
  - ask_variables_on_launch: true
    credentials:
      - Windows Kerberos Credential
    execution_environment: ee-windows
    extra_vars:
      _hosts: win11-guest-2.autodotes.local
    inventory: Proxmox Inventory
    job_slice_count: 1
    job_tags: delete
    job_type: run
    name: Windows // Long paths - Delete
    playbook: demos/delete_folder_long_path.yml
    project: Windows Mgmt
    survey_enabled: true
    survey_spec:
      description: ""
      name: ""
      spec:
        - choices: ""
          # noqa: yaml[line-length]
          default: "\\\\win11-guest-1\\c$\\Users\\Administrator\\superlongfolder\n\\\\win11-guest-1\\c$\\Users\\Administrator\\anotherlongone\n\\\\win11-guest-1\\\
            c$\\Users\\Administrator\\whyarethesenamessolong"
          max: 1024
          min: 0
          new_question: false
          question_description: "Example: \\\\win11-guest-1\\c$\\Users\\Administrator\\superlongpath"
          question_name: Enter list of paths to delete
          required: true
          type: textarea
          variable: root_folders
  - credentials:
      - Windows Kerberos Credential
    execution_environment: ee-windows
    extra_vars:
      _hosts: win11-guest-1.autodotes.local
    inventory: Proxmox Inventory
    job_slice_count: 1
    job_tags: setup
    job_type: run
    name: Windows // Long Paths - Setup
    playbook: demos/delete_folder_long_path.yml
    project: Windows Mgmt
    survey_enabled: true
    survey_spec:
      description: ""
      name: ""
      spec:
        - choices: ""
          default: "C:\\Users\\Administrator\\superlongfolder\nC:\\Users\\Administrator\\anotherlongone\nC:\\Users\\Administrator\\whyarethesenamessolong"
          max: 1024
          min: 0
          new_question: false
          question_description: C:\Users\Administrator\superlongpath
          question_name: Enter list of absolute paths to create
          required: true
          type: textarea
          variable: root_folders
  - ask_credential_on_launch: true
    ask_limit_on_launch: true
    ask_tags_on_launch: true
    credentials:
      - Autodotes[local] Admin
      - Demo SQL Service Account Credentials
      - Windows Server Credential
    description: Install a SQL Server instance using DSC
    inventory: Proxmox Inventory
    job_slice_count: 1
    job_type: run
    limit: win11-guest-1
    name: Windows // MSSQL Role
    playbook: demos/install_mssql_dsc.yml
    project: Windows Mgmt
  - credentials:
      - Red Hat Automation Hub
    execution_environment: ee-default
    inventory: Cloud Inventory
    job_slice_count: 1
    job_type: run
    limit: win-demo-1
    name: Windows // Powershell
    playbook: playbooks/pwsh.yml
    project: Windows Mgmt
