# ansible-playbook pb_aap_config.yml --tags networking,credentials --skip-tags common
---
controller_credentials_networking:
  - name: Cisco (ios) Credential
    organization: Autodotes
    description: ""
    credential_type: Machine
    inputs:
      become_method: enable
      become_password: REPLACE_ME
      become_username: ""
      password: REPLACE_ME
      username: cisco
  - name: Eve-NG (admin)
    organization: Autodotes
    description: integrate with Eve-NG API
    credential_type: Eve-NG Credential
    inputs:
      eve_ng_url: http://192.168.0.3
      eve_ng_user: admin
      eve_ng_password: REPLACE_ME
  - name: Git Role Credential
    organization: Autodotes
    description: SSH key for integration with a git role
    credential_type: Git Role
    inputs:
      git_ssh_key: "{{ controller_credential_ansible_ssh_key }}"
      git_url: git@github.com:zjleblanc/ansible-network-configs.git
  - name: Palo Alto Bastion
    organization: Autodotes
    description: Palo Alto Bastion credential for supporting SSH proxy implementation
    credential_type: SSH Proxy
    inputs:
      ssh_proxy_host: REPLACE_ME
      ssh_proxy_key: "{{ controller_credential_ansible_ssh_key }}"
      ssh_proxy_username: ec2-user
  - name: Palo Alto Demo Vault
    organization: Autodotes
    description: ""
    credential_type: Vault
    inputs:
      vault_id: ""
      vault_password: "{{ controller_credential_ansible_vault_password }}"
  - name: Palo Alto Firewall (admin)
    organization: Autodotes
    description: Palo Alto Firewall administrator credentials compatible with the palaltonetworks.panos collection
    credential_type: Palo Alto Networks Provider
    inputs:
      panos_ip_address: 18.223.60.25
      panos_password: REPLACE_ME
      panos_username: admin
  - name: panos-demo-t1-fw
    organization: Autodotes
    description: Palo Alto Firewall administrator credentials compatible with the palaltonetworks.panos collection
    credential_type: Palo Alto Networks Provider
    inputs:
      panos_ip_address: 3.23.218.149
      panos_password: REPLACE_ME
      panos_port: ""
      panos_serial_number: ""
      panos_username: admin
  - name: Personal Slack Token
    organization: Autodotes
    description: Posting to Autodotes Slack organization
    credential_type: Slack API Token
    inputs:
      raw_slack_token: "{{ controller_credential_slack_token }}"
