# ansible-playbook pb_aap_config.yml --tags networking,credential_types --skip-tags common
---
controller_credential_types_networking:
  - name: Eve-NG Credential
    description: for integration with the eve-ng api
    kind: cloud
    injectors:
      extra_vars:
        eve_ng_password: !unsafe "{{ eve_ng_password }}"
        eve_ng_url: !unsafe "{{ eve_ng_url }}"
        eve_ng_user: !unsafe "{{ eve_ng_user }}"
    inputs:
      fields:
        - id: eve_ng_url
          label: Eve-NG URL
          type: string
        - id: eve_ng_user
          label: Eve-NG User
          type: string
        - id: eve_ng_password
          label: Eve-NG Password
          secret: true
          type: string
      required:
        - eve_ng_url
        - eve_ng_user
        - eve_ng_password
  - name: Git Role
    description: Specifically for use with git role in network-mgmt project
    kind: cloud
    injectors:
      extra_vars:
        git_ssh_key: !unsafe "{{ git_ssh_key }}"
        git_url: !unsafe "{{ git_url }}"
    inputs:
      fields:
        - id: git_url
          label: Git URL
          type: string
        - format: ssh_private_key
          id: git_ssh_key
          label: Git SSH Private Key
          multiline: true
          secret: true
          type: string
      required:
        - git_url
        - git_ssh_key
  - name: Palo Alto Networks Provider
    description: for use with the paloaltonetworks.panos collection
    kind: cloud
    injectors:
      extra_vars:
        panos_provider:
          ip_address: !unsafe "{{ panos_ip_address }}"
          password: !unsafe "{{ panos_password | default(omit) }}"
          username: !unsafe "{{ panos_username | default(omit) }}"
    inputs:
      fields:
        - help_text: The IP address or hostname of the PAN-OS device being configured.
          id: panos_ip_address
          label: IP Address
          type: string
        - help_text: The port number to connect to the PAN-OS device on.
          id: panos_port
          label: Port
          type: string
        - help_text: The serial number of a firewall to use for targeted commands. If ip_address is not a Panorama PAN-OS device, then this param is ignored.
          id: panos_serial_number
          label: Serial Number
          type: string
        - help_text: The username to use for authentication. This is ignored if api_key is specified.
          id: panos_username
          label: Username
          type: string
        - help_text: The password to use for authentication. This is ignored if api_key is specified.
          id: panos_password
          label: Password
          secret: true
          type: string
        - help_text: The API key to use instead of generating it using username / password.
          id: panos_api_key
          label: API Key
          secret: true
          type: string
      required:
        - panos_ip_address
