# ansible-playbook pb_aap_config.yml --tags networking,projects --skip-tags common
---
controller_projects_networking:
  - name: Network Mgmt
    organization: Autodotes
    scm_branch: master
    scm_clean: "no"
    scm_delete_on_update: "no"
    scm_type: git
    scm_update_on_launch: "no"
    scm_url: https://github.com/zjleblanc/ansible-network-mgmt.git
